spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UsersDB-Task
    username: postgres
    password: password
  liquibase:
    change-log: db/changelog/main-changelog.yml
