spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UsersDB-Task
    username: Elbek-G
    password: 123
  liquibase:
    change-log: db/changelog/main-changelog.yml
